/**
 * THE WHOLE-REPOSITORY IMPORT GRAPH, as one machine-checkable artifact.
 *
 * WHAT THIS ADDS THAT THE EIGHT ISOLATION TESTS DO NOT. Layering in this repository is enforced by
 * seven per-directory allowlists plus a security gate, each with its own copy of an import regex.
 * That is strong where it looks and silent where it does not, and three areas were never looked at
 * at all: `lib/providers/`, `lib/doctor/`, and the top-level `lib/*.mjs` files. Nothing built a
 * whole-repository edge list, and nothing detected a cycle.
 *
 * It also replaces luck with reading. Measured against the 199 distinct edges in `plugins/**`, the
 * single-line regex in `telemetry.isolation.test.mjs` and `hook.security.test.mjs` cannot see 23 of
 * them, because it cannot match a multi-line `import {\n ... \n} from`. Two of those 23 matter:
 *
 *   - the dispatch allowlist (`telemetry.isolation.test.mjs:181`) never sees
 *     `dispatch/index.mjs -> ./contract.mjs` or `-> ../context-budget.mjs`. Both ARE permitted, so
 *     that test passes today by luck rather than by having read the edge.
 *   - the routing-purity test (`telemetry.isolation.test.mjs:100`) cannot see a multi-line
 *     `import {\n ... \n} from 'node:fs'`. CLAUDE.md's second non-negotiable is presently held by a
 *     raw-source `/node:/` check in a DIFFERENT file.
 *
 * Every edge in this file is read with `test/helpers/imports.mjs`, which is a lexer rather than a
 * regex and is a measured strict superset of all four existing bodies.
 *
 * WHY TWO DECLARATIONS AND NOT A RANK ALONE. A rank permits every DOWNWARD edge, so a rank alone
 * would allow `dispatch -> routing.mjs` and `telemetry -> routing.mjs` — which are exactly the two
 * edges `telemetry.isolation.test.mjs:90` and `:217` exist to ban. So a legal direction is not
 * sufficient: RANK fixes the order of the pipeline, and ALLOWED_TARGETS fixes who may speak to whom.
 *
 * WHY PER FILE AND NOT PER DIRECTORY. Three directories are not homogeneous.
 * `providers/capability.mjs`, `governance/policy.mjs` and `doctor/report.mjs` import nothing and are
 * read by layers that must not touch their directories. Declaring them as rank-0 shared leaves is
 * what CLAUDE.md already says about them in prose, and it means `config.mjs -> capability.mjs`,
 * `dispatch/modes.mjs -> routing-policy.mjs` and `redact.mjs`'s seven importers are legal BY
 * CONSTRUCTION rather than by exemption. The justification lives on the leaf.
 */

import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import test from 'node:test'

import { scanImports } from './helpers/imports.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(HERE, '..')
const TEST_DIR = HERE

const slash = (p) => p.split(path.sep).join('/')
const read = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8')

/* ------------------------------------------------------------------ the two plugins */

const ROUTER = 'plugins/model-router'
const DASHBOARD = 'plugins/router-dashboard'

/**
 * Rank 0, module 'leaf': imports NO relative module at all.
 *
 * The reason strings are the point. A leaf is the mechanism that lets a low layer and a high layer
 * share a fact without either importing the other, so "why is this a leaf" is the same question as
 * "why is that cross-layer read safe".
 */
const LEAVES = Object.freeze({
  [`${ROUTER}/lib/version.mjs`]:
    'generated by scripts/sync-version.mjs. It exists so telemetry/record.mjs can state the release ' +
    'without a readFileSync of a manifest on the hook hot path.',
  [`${ROUTER}/lib/globs.mjs`]:
    'pure path matching. The deny list is a security control, so it must be testable with no graph.',
  [`${ROUTER}/lib/routing-policy.mjs`]:
    'SHARED VOCABULARY. The reason and policy tables, read by routing.mjs, dispatch/modes.mjs and ' +
    'scripts/doctor.mjs. A leaf rather than "part of the routing layer", because three layers ' +
    'legitimately need the vocabulary and none of them but routing.mjs may call decide(). The ' +
    'EXPECTED_IMPORTERS pin on routing.mjs is what keeps that distinction honest.',
  [`${ROUTER}/lib/context-budget.mjs`]:
    'the context model, pure and import-free, which is what lets dispatch and the doctor reason ' +
    'about a window without loading a provider. CLAUDE.md names this as load-bearing.',
  [`${ROUTER}/lib/redact.mjs`]:
    'SHARED by telemetry/ and providers/. Shared rather than copied, because a second ' +
    'secret-scrubbing regex set is a second thing that can fall behind the first.',
  [`${ROUTER}/lib/providers/capability.mjs`]:
    'MODULE OVERRIDE: it lives under providers/ but is NOT the providers layer. A capability record ' +
    'describes a provider model; importing it loads no provider and opens no socket. That is what ' +
    'makes config.mjs -> providers/capability.mjs an ordinary downward edge instead of an exception.',
  [`${ROUTER}/lib/governance/policy.mjs`]:
    'MODULE OVERRIDE: the pure budget decision plus describeGovernance(). Read by scripts/budget.mjs ' +
    'and scripts/doctor.mjs, which must be able to render governance WITHOUT opening a ledger.',
  [`${ROUTER}/lib/doctor/report.mjs`]:
    'MODULE OVERRIDE: the pure severity model. scripts/doctor.mjs only renders it — the same split ' +
    'governance/policy.mjs already uses.',
  [`${ROUTER}/lib/env-registry.mjs`]:
    'a frozen declaration, compared against a source scan in both directions by env.inventory.test.mjs.',
  [`${ROUTER}/lib/cli.mjs`]:
    'flag parser, colour policy and exit-code table. It imports nothing, which is part of why ' +
    'router-dashboard CANNOT import it; cli.contract.test.mjs enforces the shared contract instead.',
  [`${ROUTER}/lib/config-descriptions.mjs`]: 'prose for every SPEC leaf, used to generate the settings table and the environment reference. ' +
    'Separate from config.mjs so that documentation text is not on the hook hot path.',
  [`${ROUTER}/lib/telemetry/pricing-lookup.mjs`]: 'pure rate resolution: a model name and a table in, a rate or null out. Import-free so that ' +
    'pricing can be reasoned about without the record schema or a provider.',
  [`${ROUTER}/lib/telemetry/pricing-table.mjs`]: 'the bundled rate table. EVERY rate ships null, so a default install reports no dollar figure ' +
    'at all; a leaf because an unpriced model must be null rather than a guessed rate.',
  [`${ROUTER}/lib/telemetry/segments.mjs`]: 'pure filename arithmetic over the store layout — rotation, pid sharding, date keys and the ' +
    'retention cutoff. Import-free, so segment selection is testable against a frozen clock.',
  [`${ROUTER}/lib/telemetry/validate.mjs`]: 'pure field validation. It decides whether a value is a number, not whether the number is ' +
    'right, so it needs nothing but the value.',
  [`${ROUTER}/lib/telemetry/identity.mjs`]:
    'salted hashing. node:crypto and node:fs only, and no relative edge, so an identity can be ' +
    'reasoned about without the record schema.',
  [`${ROUTER}/lib/analytics/window.mjs`]: 'calendar arithmetic over UTC half-open windows, testable against a frozen number. The whole ' +
    'analytics layer has no ambient clock, and this leaf is why it does not need one.',
  [`${ROUTER}/lib/hook/adapter.mjs`]:
    'the protocol translation. It imports NOTHING AT ALL, which is what lets it be tested against ' +
    'hostile host input with no graph behind it (hook.security.test.mjs:141).',
  [`${ROUTER}/lib/hook/event.mjs`]: 'the telemetry mapping for a hook row: which columns a gate-only row nulls, and which a ' +
    'delegated row fills. It decides nothing, so it imports nothing.',

  [`${DASHBOARD}/lib/contract.mjs`]: 'the shape the reader accepts, and the contract version it will render. Import-free, so the ' +
    'dashboard can reject an incompatible response without any router code present.',
  [`${DASHBOARD}/lib/format.mjs`]: 'number and null formatting, and the one place a null becomes a visible gap rather than a zero. ' +
    'A leaf because that rule must hold with no data source behind it.',
  [`${DASHBOARD}/lib/html.mjs`]: 'escaping and element assembly. No network, no node builtin and no external URL, which is what ' +
    'makes the generated report one self-contained file.',
  [`${DASHBOARD}/lib/version.mjs`]: 'generated by scripts/sync-version.mjs. Nothing under router-dashboard/lib may import a node ' +
    'builtin, so the renderer physically cannot open its own manifest to find its version.',
  [`${DASHBOARD}/scripts/collect.mjs`]:
    'the one file in the dashboard permitted to spawn. It imports no relative module, so "it cannot ' +
    'read a store" stays structural: it can only ask the router CLI and parse what comes back.',
})

/**
 * rank, module. Lower rank is more fundamental. The gaps between ranks are deliberate: a new layer
 * has to be given a number, which is a decision somebody makes rather than a default it inherits.
 *
 * The frozen pipeline, as numbers:
 *   routing(20) -> governance(30) -> capability/providers(40) -> dispatch(50) -> telemetry(60)
 *   -> analytics(70) -> hook(80) -> entry(90) -> scripts(95), and dashboard as its own graph.
 */
const RANKED = Object.freeze({
  // ---- 10 · config. Reads the context model and nothing else.
  [`${ROUTER}/lib/config.mjs`]: { rank: 10, module: 'config' },
  [`${ROUTER}/lib/config-schema.mjs`]: { rank: 11, module: 'config' },
  [`${ROUTER}/lib/config-doc.mjs`]: { rank: 11, module: 'config' },

  // ---- 20 · routing. "Would this be APPROPRIATE to delegate?" — the first of CLAUDE.md's three.
  [`${ROUTER}/lib/routing.mjs`]: { rank: 20, module: 'routing' },

  // ---- 30 · governance. "Are we currently ALLOWED to?" — the second.
  [`${ROUTER}/lib/governance/ledger.mjs`]: { rank: 30, module: 'governance' },
  [`${ROUTER}/lib/governance/index.mjs`]: { rank: 31, module: 'governance' },

  // ---- 40 · providers. The first swap point.
  [`${ROUTER}/lib/providers/contract.mjs`]: { rank: 40, module: 'providers' },
  [`${ROUTER}/lib/providers/gemini.mjs`]: { rank: 41, module: 'providers' },
  [`${ROUTER}/lib/providers/mock.mjs`]: { rank: 41, module: 'providers' },
  [`${ROUTER}/lib/providers/ollama.mjs`]: { rank: 41, module: 'providers' },
  [`${ROUTER}/lib/providers/index.mjs`]: { rank: 42, module: 'providers' },

  // ---- 50 · dispatch. "CAN this worker run it?" — the third.
  [`${ROUTER}/lib/dispatch/modes.mjs`]: { rank: 50, module: 'dispatch' },
  [`${ROUTER}/lib/dispatch/task.mjs`]: { rank: 50, module: 'dispatch' },
  [`${ROUTER}/lib/dispatch/contract.mjs`]: { rank: 50, module: 'dispatch' },
  [`${ROUTER}/lib/dispatch/index.mjs`]: { rank: 51, module: 'dispatch' },

  // ---- 60 · telemetry. It records a decision that has already been made.
  [`${ROUTER}/lib/telemetry/record.mjs`]: { rank: 60, module: 'telemetry' },
  [`${ROUTER}/lib/telemetry/calc.mjs`]: { rank: 61, module: 'telemetry' },
  [`${ROUTER}/lib/telemetry/aggregate.mjs`]: { rank: 61, module: 'telemetry' },
  [`${ROUTER}/lib/telemetry/contract.mjs`]: { rank: 61, module: 'telemetry' },
  [`${ROUTER}/lib/telemetry/pricing-load.mjs`]: { rank: 61, module: 'telemetry' },
  [`${ROUTER}/lib/telemetry/event.mjs`]: { rank: 62, module: 'telemetry' },
  [`${ROUTER}/lib/telemetry/jsonl.mjs`]: { rank: 62, module: 'telemetry' },
  [`${ROUTER}/lib/telemetry/null-sink.mjs`]: { rank: 62, module: 'telemetry' },
  [`${ROUTER}/lib/telemetry/index.mjs`]: { rank: 63, module: 'telemetry' },

  // ---- 70 · analytics. The READ model, and the fourth separate decision layer.
  [`${ROUTER}/lib/analytics/schema.mjs`]: { rank: 70, module: 'analytics' },
  [`${ROUTER}/lib/analytics/aggregates.mjs`]: { rank: 71, module: 'analytics' },
  [`${ROUTER}/lib/analytics/predicates.mjs`]: { rank: 71, module: 'analytics' },
  [`${ROUTER}/lib/analytics/select.mjs`]: { rank: 71, module: 'analytics' },
  [`${ROUTER}/lib/analytics/text.mjs`]: { rank: 71, module: 'analytics' },
  [`${ROUTER}/lib/analytics/quality.mjs`]: { rank: 72, module: 'analytics' },
  [`${ROUTER}/lib/analytics/serialize.mjs`]: { rank: 72, module: 'analytics' },
  [`${ROUTER}/lib/analytics/metrics.mjs`]: { rank: 73, module: 'analytics' },
  [`${ROUTER}/lib/analytics/segments.mjs`]: { rank: 73, module: 'analytics' },
  [`${ROUTER}/lib/analytics/index.mjs`]: { rank: 74, module: 'analytics' },

  // ---- 80 · the hook. The only composition point on the hot path, and the only impure layer.
  [`${ROUTER}/lib/hook/facts.mjs`]: { rank: 80, module: 'hook' },
  [`${ROUTER}/lib/hook/intent.mjs`]: { rank: 81, module: 'hook' },
  [`${ROUTER}/lib/hook/run.mjs`]: { rank: 82, module: 'hook' },

  // ---- 90 · the process entry point.
  [`${ROUTER}/hooks/pre-tool-use.mjs`]: { rank: 90, module: 'entry' },

  // ---- 95 · scripts. They render; they never decide.
  [`${ROUTER}/scripts/analytics.mjs`]: { rank: 95, module: 'scripts' },
  [`${ROUTER}/scripts/budget.mjs`]: { rank: 95, module: 'scripts' },
  [`${ROUTER}/scripts/doctor.mjs`]: { rank: 95, module: 'scripts' },
  [`${ROUTER}/scripts/prune.mjs`]: { rank: 95, module: 'scripts' },
  [`${ROUTER}/scripts/smoke-hook.mjs`]: { rank: 95, module: 'scripts' },
  [`${ROUTER}/scripts/gen-config-doc.mjs`]: { rank: 95, module: 'scripts' },
  [`${ROUTER}/scripts/gen-config-schema.mjs`]: { rank: 95, module: 'scripts' },
  [`${ROUTER}/scripts/gen-env-docs.mjs`]: { rank: 95, module: 'scripts' },

  // ---- router-dashboard: a SECOND, DISJOINT graph. Its ranks are its own.
  [`${DASHBOARD}/lib/render/chart.mjs`]: { rank: 1, module: 'dashboard-render' },
  [`${DASHBOARD}/lib/render/sections.mjs`]: { rank: 2, module: 'dashboard-render' },
  [`${DASHBOARD}/lib/render/index.mjs`]: { rank: 3, module: 'dashboard-render' },
  [`${DASHBOARD}/scripts/report.mjs`]: { rank: 10, module: 'dashboard-scripts' },
})

/** Every declared file, leaves included. */
const ALL = Object.freeze({
  ...Object.fromEntries(Object.keys(LEAVES).map((f) => [f, { rank: 0, module: 'leaf' }])),
  ...RANKED,
})

/**
 * Which MODULES a module may point at. 'leaf' is implicit for everything; the rest is named.
 *
 * This is the half a rank cannot express. `dispatch -> routing.mjs` is a legal downward edge and is
 * nevertheless forbidden, because the dispatcher must not be able to re-ask the question the gate
 * owns. Same for `telemetry -> routing`, and for anything at all pointing back into `hook/`.
 */
const ALLOWED_TARGETS = Object.freeze({
  // A leaf points at nothing. Asserted below rather than assumed.
  leaf: Object.freeze([]),
  config: Object.freeze(['config']),
  // Leaves only. CLAUDE.md non-negotiables 2 and 9: no provider, no network, no governance.
  routing: Object.freeze([]),
  // Never a provider, never routing, never dispatch. Governance runs AFTER decide() has ruled.
  governance: Object.freeze(['governance']),
  providers: Object.freeze(['providers']),
  dispatch: Object.freeze(['dispatch', 'providers']),
  // Never dispatch, never providers, never analytics. Telemetry is written to, not read from.
  telemetry: Object.freeze(['telemetry']),
  analytics: Object.freeze(['analytics', 'telemetry']),
  hook: Object.freeze([
    'hook', 'config', 'routing', 'governance', 'dispatch', 'providers', 'telemetry',
  ]),
  entry: Object.freeze(['config', 'hook']),
  scripts: Object.freeze([
    'config', 'governance', 'providers', 'dispatch', 'telemetry', 'analytics',
  ]),
  'dashboard-render': Object.freeze(['dashboard-render']),
  'dashboard-scripts': Object.freeze(['dashboard-render']),
})

/**
 * Every node builtin the two plugins may touch, per file. EXACT, and empty by default.
 *
 * WHY THIS IS HERE AND NOT ONLY IN THE PER-LAYER TESTS. Planting a multi-line
 * `import {\n readFileSync,\n} from 'node:fs'` into routing.mjs was caught by exactly ONE
 * assertion in the whole suite — `routing.capability.test.mjs:158`'s raw-source /node:/ scan.
 * `telemetry.isolation.test.mjs:100`, whose stated job is routing purity, did not see it, because
 * its regex is single-line. CLAUDE.md's second non-negotiable deserves better than one
 * coincidental check in an unrelated file.
 *
 * An empty default is what makes this strong: a new builtin anywhere in the engine fails until
 * somebody writes it down. That is also how `node:child_process` stays confined to the two files
 * allowed to spawn, without a separate ban.
 */
const BUILTINS = Object.freeze({
  // The only impure layer on the hot path, and it may use exactly two builtins.
  [`${ROUTER}/hooks/pre-tool-use.mjs`]: Object.freeze(['node:fs']),
  [`${ROUTER}/lib/hook/facts.mjs`]: Object.freeze(['node:fs']),
  [`${ROUTER}/lib/hook/intent.mjs`]: Object.freeze(['node:fs']),
  [`${ROUTER}/lib/hook/run.mjs`]: Object.freeze(['node:fs']),
  // Config reads layers off disk and expands a home directory.
  [`${ROUTER}/lib/config.mjs`]: Object.freeze(['node:fs', 'node:os', 'node:path']),
  // Governance: the ledger and its lock. No network, by directory census elsewhere.
  [`${ROUTER}/lib/governance/index.mjs`]: Object.freeze(['node:fs']),
  [`${ROUTER}/lib/governance/ledger.mjs`]: Object.freeze(['node:fs', 'node:path']),
  // Telemetry: the sink, the salt and the segment paths. Four files, and no more.
  [`${ROUTER}/lib/telemetry/identity.mjs`]: Object.freeze(['node:crypto', 'node:fs', 'node:path']),
  [`${ROUTER}/lib/telemetry/index.mjs`]: Object.freeze(['node:crypto', 'node:fs']),
  [`${ROUTER}/lib/telemetry/jsonl.mjs`]: Object.freeze(['node:fs']),
  [`${ROUTER}/lib/telemetry/pricing-load.mjs`]: Object.freeze(['node:fs']),
  [`${ROUTER}/lib/telemetry/segments.mjs`]: Object.freeze(['node:path']),
  // Scripts render and may read. Only smoke-hook may spawn, and it spawns the real hook.
  [`${ROUTER}/scripts/budget.mjs`]: Object.freeze(['node:path']),
  [`${ROUTER}/scripts/doctor.mjs`]: Object.freeze(['node:fs', 'node:os', 'node:path', 'node:url']),
  [`${ROUTER}/scripts/gen-config-doc.mjs`]: Object.freeze(['node:fs', 'node:path', 'node:url']),
  [`${ROUTER}/scripts/gen-config-schema.mjs`]: Object.freeze(['node:fs', 'node:path', 'node:url']),
  [`${ROUTER}/scripts/gen-env-docs.mjs`]: Object.freeze(['node:fs', 'node:path', 'node:url']),
  [`${ROUTER}/scripts/smoke-hook.mjs`]: Object.freeze([
    'node:child_process', 'node:fs', 'node:os', 'node:path', 'node:url',
  ]),
  // The dashboard: nothing under lib/, and the one permitted spawn.
  [`${DASHBOARD}/scripts/collect.mjs`]: Object.freeze([
    'node:child_process', 'node:fs', 'node:path', 'node:url',
  ]),
  [`${DASHBOARD}/scripts/report.mjs`]: Object.freeze(['node:fs', 'node:path']),
})

/**
 * Files whose reach must be NARROWER than their module's.
 *
 * `hook/facts.mjs` is the whole reason this exists. It is a measurement module, and it is the only
 * place in the repository where one reaches down into dispatch and providers. Its module permits
 * those directories, so without this entry it could grow an edge to `dispatch/task.mjs` — the hook
 * building its own worker request — and nothing would notice.
 */
const FILE_TARGETS = Object.freeze({
  [`${ROUTER}/lib/hook/facts.mjs`]: Object.freeze({
    allow: Object.freeze([
      `${ROUTER}/lib/dispatch/index.mjs`,
      `${ROUTER}/lib/providers/index.mjs`,
    ]),
    reason:
      'resolveWorker() is the one fact the gate needs about which worker WOULD run: a provider id ' +
      'and a model string. facts.mjs asks dispatch rather than re-deriving it, because two answers ' +
      'to "which worker" is how the telemetry row and the actual call come to disagree. The ' +
      'providers edge is readinessFor()/billingFor()/isKnownProvider() — three table lookups, and ' +
      '`billing` is carried because governance needs exactly one fact about the provider and must ' +
      'get it WITHOUT loading a provider module. That is only safe while providers/index.mjs keeps ' +
      'its registry lazy, so this entry is also a note on what that laziness is load-bearing for.',
  }),
})

/**
 * Who is ALLOWED to import these. The rank rule permits every downward edge, so without a positive
 * pin a second caller could appear and the ordering guarantee — routing, then governance, then
 * capability — would stop being a property of one file.
 *
 * governance/index.mjs is deliberately ABSENT: governance.isolation.test.mjs:212 already pins its
 * caller census, and a duplicated assertion is a second thing to keep in step.
 */
const EXPECTED_IMPORTERS = Object.freeze({
  [`${ROUTER}/lib/routing.mjs`]: Object.freeze([`${ROUTER}/lib/hook/run.mjs`]),
  [`${ROUTER}/lib/dispatch/task.mjs`]: Object.freeze([`${ROUTER}/lib/hook/run.mjs`]),
  [`${ROUTER}/lib/hook/run.mjs`]: Object.freeze([`${ROUTER}/hooks/pre-tool-use.mjs`]),
  [`${ROUTER}/lib/telemetry/index.mjs`]: Object.freeze([
    `${ROUTER}/lib/analytics/index.mjs`,
    `${ROUTER}/lib/hook/run.mjs`,
    `${ROUTER}/scripts/doctor.mjs`,
  ]),
})

/* ------------------------------------------------------------------ build the graph */

const walk = (dir, out = []) => {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name === 'node_modules' || e.name === '.git' || e.name === '.tmp') continue
    const p = path.join(dir, e.name)
    if (e.isDirectory()) walk(p, out)
    else if (e.name.endsWith('.mjs')) out.push(p)
  }
  return out
}

const filesOnDisk = () =>
  walk(path.join(ROOT, 'plugins'))
    .map((p) => slash(path.relative(ROOT, p)))
    .sort()

/** [{from, to, spec}] for every relative specifier, plus the builtins and unresolvables. */
const buildGraph = () => {
  const edges = []
  const builtins = new Map()
  const computed = []
  for (const rel of filesOnDisk()) {
    const { specs, computed: c } = scanImports(read(rel))
    if (c.length > 0) computed.push({ file: rel, forms: c })
    for (const spec of specs) {
      if (!spec.startsWith('.')) {
        if (!builtins.has(rel)) builtins.set(rel, [])
        builtins.get(rel).push(spec)
        continue
      }
      const to = slash(path.relative(ROOT, path.resolve(path.dirname(path.join(ROOT, rel)), spec)))
      edges.push({ from: rel, to, spec })
    }
  }
  return { edges, builtins, computed }
}

const GRAPH = buildGraph()
const EDGES = GRAPH.edges
const BY_SOURCE = new Map()
for (const e of EDGES) {
  if (!BY_SOURCE.has(e.from)) BY_SOURCE.set(e.from, [])
  BY_SOURCE.get(e.from).push(e.to)
}
const outDegree = (f) => (BY_SOURCE.get(f) ?? []).length
const pluginOf = (f) => (f.startsWith(`${DASHBOARD}/`) ? 'router-dashboard' : 'model-router')

/* ------------------------------------------------------------------------- census */

test('the graph covers exactly the .mjs files on disk, in both directions', () => {
  // Exact equality BOTH WAYS. A new file must be ranked deliberately, and a deleted file must drop
  // out of the table. This is the test that gives every other assertion in this file its meaning:
  // see dashboard.isolation.test.mjs's header for what a ban that scans nothing looks like after
  // nine phases of passing.
  assert.deepEqual(filesOnDisk(), Object.keys(ALL).sort())
})

test('the scan found edges, and found them in every file that declares a dependency', () => {
  // ANTI-VACUITY, two-sided. A broken scanner returns [] for everything, and then every ban below
  // passes while checking nothing.
  assert.ok(EDGES.length >= 150, `only ${EDGES.length} edges found; the scanner is broken`)
  const silentButRanked = Object.keys(RANKED).filter((f) => outDegree(f) === 0).sort()
  assert.deepEqual(silentButRanked, [], 'a ranked, non-leaf file produced no edges at all')
})

test('every declared leaf imports no relative module, and every import-free file is declared', () => {
  // The POSITIVE half, and the one that keeps the model honest. LEAVES is the mechanism that makes
  // config.mjs -> providers/capability.mjs legal, so a leaf that quietly grows an import must fail
  // HERE — not silently widen what a cross-layer read is allowed to mean.
  const grown = Object.keys(LEAVES).filter((f) => outDegree(f) > 0).sort()
  assert.deepEqual(grown, [], 'a declared leaf acquired a relative import')
  const undeclared = Object.keys(RANKED).filter((f) => outDegree(f) === 0).sort()
  assert.deepEqual(undeclared, [], 'an import-free file must be declared in LEAVES, with a reason')
})

test('every leaf carries a reason of substance, because a flag explains nothing', () => {
  for (const [file, reason] of Object.entries(LEAVES)) {
    assert.equal(typeof reason, 'string', file)
    assert.ok(reason.length > 40, `${file}: a leaf needs a sentence, not a label`)
  }
})

test('no specifier in the product tree is computed, so no edge can hide behind a template', () => {
  // A dynamic import of a built-up path is an edge this scanner cannot resolve. It must FAIL the
  // graph rather than vanish from it. Zero today — providers/index.mjs loads its three modules by
  // literal specifier, which is what makes the lazy registry auditable.
  assert.deepEqual(GRAPH.computed, [])
})

/* -------------------------------------------------------------------- the rank rule */

test('every edge points downward, or sideways within one module', () => {
  // The frozen pipeline, as an arithmetic property of 199 edges rather than a diagram in a document.
  const violations = []
  for (const { from, to, spec } of EDGES) {
    const a = ALL[from]
    const b = ALL[to]
    assert.ok(a, `unranked source ${from}`)
    assert.ok(b, `unranked target ${to} (from ${from})`)
    const downward = b.rank < a.rank
    const sideways = b.rank === a.rank && b.module === a.module
    if (!downward && !sideways) {
      violations.push(`${from} (${a.module}/${a.rank}) -> ${spec} (${b.module}/${b.rank})`)
    }
  }
  assert.deepEqual(violations, [], 'an upward or cross-module-sideways import')
})

test('every edge points at a module its source is allowed to speak to', () => {
  // The half the rank cannot express. dispatch -> routing.mjs is downward AND forbidden.
  const violations = []
  for (const { from, to } of EDGES) {
    const srcModule = ALL[from].module
    const dstModule = ALL[to].module
    if (dstModule === 'leaf') continue
    if (!ALLOWED_TARGETS[srcModule].includes(dstModule)) {
      violations.push(`${from} (${srcModule}) -> ${to} (${dstModule})`)
    }
  }
  assert.deepEqual(violations, [], 'a module reached a module it may not reach')
})

test('a file with a narrowed reach keeps it, and the narrowing is still needed', () => {
  for (const [file, { allow, reason }] of Object.entries(FILE_TARGETS)) {
    assert.ok(reason.length > 80, `${file}: a narrowing needs its argument written down`)
    const crossModule = (BY_SOURCE.get(file) ?? [])
      .filter((to) => ALL[to].module !== 'leaf' && ALL[to].module !== ALL[file].module)
      .sort()
    assert.deepEqual([...new Set(crossModule)], [...allow].sort(), `${file} reaches past its module`)
    // A narrowing nobody takes is a rule nobody is enforcing. If facts.mjs stops reaching out of
    // its module entirely, delete the entry rather than leaving a stale exemption behind.
    assert.ok(crossModule.length > 0, `${file}: the narrowing is stale — no cross-module edge left`)
  }
})

test('the layers CLAUDE.md names as separate decisions do not import each other', () => {
  // Stated as the three questions rather than as directory names, because that is the claim:
  // routing answers "appropriate", governance answers "allowed", dispatch answers "can".
  const forbidden = [
    ['routing', 'governance', 'a budget must not be able to rewrite a routing classification'],
    ['routing', 'dispatch', 'the gate must not know which worker would run'],
    ['routing', 'providers', 'the gate imports no provider — CLAUDE.md non-negotiable 2'],
    ['routing', 'telemetry', 'the gate records nothing'],
    ['governance', 'routing', 'governance runs AFTER decide() has ruled and never reaches back'],
    ['governance', 'dispatch', 'governance does not execute'],
    ['governance', 'providers', 'governance learns billing from a table, not from a provider'],
    ['dispatch', 'routing', 'the executor must not re-ask the question the gate owns'],
    ['dispatch', 'governance', 'the executor does not spend'],
    ['dispatch', 'telemetry', 'the dispatcher writes no row'],
    ['telemetry', 'routing', 'a record must not be able to change what it records'],
    ['telemetry', 'dispatch', 'the sink does not call a worker'],
    ['telemetry', 'analytics', 'the write model must not depend on the read model'],
    ['analytics', 'routing', 'the read model decides nothing'],
    ['analytics', 'governance', 'analytics reads stored money; it does not evaluate a budget'],
    ['analytics', 'dispatch', 'analytics calls nothing'],
    ['analytics', 'providers', 'analytics imports no provider and no pricing module'],
  ]
  const violations = []
  for (const [src, dst, why] of forbidden) {
    for (const { from, to } of EDGES) {
      if (ALL[from].module === src && ALL[to].module === dst) violations.push(`${from} -> ${to}: ${why}`)
    }
  }
  assert.deepEqual(violations, [])
})

test('nothing in the engine imports the hook adapter layer', () => {
  // The hook is the only impure layer on the hot path. The engine must stay testable without it.
  const violations = EDGES
    .filter((e) => ALL[e.to].module === 'hook' && !['hook', 'entry'].includes(ALL[e.from].module))
    .map((e) => `${e.from} -> ${e.to}`)
  assert.deepEqual(violations, [])
})

/* ------------------------------------------------------- the positive importer pins */

test('the files with exactly one caller still have exactly that caller', () => {
  for (const [target, expected] of Object.entries(EXPECTED_IMPORTERS)) {
    const actual = [...new Set(EDGES.filter((e) => e.to === target).map((e) => e.from))].sort()
    assert.deepEqual(actual, [...expected].sort(), `importers of ${target}`)
  }
})

/* --------------------------------------------------------- the two-plugin boundary */

test('no edge crosses the plugin boundary, in either direction', () => {
  // Stronger than a substring ban on the other plugin's name, because it also catches a relative
  // traversal — ../../model-router/lib/... — which spells neither plugin's name in the specifier.
  const crossing = EDGES
    .filter((e) => pluginOf(e.from) !== pluginOf(e.to))
    .map((e) => `${e.from} -> ${e.to}`)
  assert.deepEqual(crossing, [], 'the two plugins must be two disjoint graphs')
})

test('nothing under router-dashboard/lib imports a node builtin', () => {
  // This is what makes "the reader cannot read a store" structural rather than a policy. Already
  // pinned by dashboard.isolation.test.mjs; repeated here because the graph has the data and an
  // unchecked builtin list in a census is a list nobody reads.
  const offenders = []
  for (const [file, specs] of GRAPH.builtins) {
    if (file.startsWith(`${DASHBOARD}/lib/`)) offenders.push(`${file}: ${specs.join(' ')}`)
  }
  assert.deepEqual(offenders, [])
})

/* --------------------------------------------------------------- node builtins */

test('every node builtin either is declared for that file, or is not there', () => {
  // Exact and empty-by-default, in both directions. This is the assertion that closes the
  // multi-line hole: a `import {\n readFileSync,\n} from 'node:fs'` anywhere in the engine now
  // fails here, whatever shape it is written in, because the lexer does not care about newlines.
  const actual = new Map(
    [...GRAPH.builtins].map(([f, specs]) => [f, [...new Set(specs)].sort()]),
  )
  const violations = []
  for (const [file, specs] of actual) {
    const allowed = BUILTINS[file] ?? []
    for (const spec of specs) {
      if (!allowed.includes(spec)) violations.push(`${file} imports ${spec}, undeclared`)
    }
  }
  for (const [file, allowed] of Object.entries(BUILTINS)) {
    const specs = actual.get(file) ?? []
    for (const spec of allowed) {
      // A stale allowance is a rule nobody is enforcing. Delete it rather than carry it.
      if (!specs.includes(spec)) violations.push(`${file} no longer imports ${spec}; undeclare it`)
    }
  }
  assert.deepEqual(violations, [])
})

test('the pure layers import no builtin at all, named one at a time', () => {
  // The same facts as above, restated as the CLAIMS they are, so a failure reads as the rule that
  // broke rather than as a diff. CLAUDE.md names each of these; this is where they are checked.
  const pure = [
    [`${ROUTER}/lib/routing.mjs`, 'the gate is synchronous, makes no network call and reads no disk'],
    [`${ROUTER}/lib/routing-policy.mjs`, 'the policy tables are data'],
    [`${ROUTER}/lib/globs.mjs`, 'the deny list is pure matching'],
    [`${ROUTER}/lib/context-budget.mjs`, 'the context model imports NOTHING — CLAUDE.md layout note'],
    [`${ROUTER}/lib/providers/capability.mjs`, 'a capability record loads no provider'],
    [`${ROUTER}/lib/governance/policy.mjs`, 'the budget decision is a pure object walk'],
    [`${ROUTER}/lib/doctor/report.mjs`, 'the severity model is pure; the script renders it'],
    [`${ROUTER}/lib/dispatch/task.mjs`, 'the task builder is pure, and is the redaction boundary'],
    [`${ROUTER}/lib/hook/adapter.mjs`, 'the protocol translation imports nothing at all'],
    [`${ROUTER}/lib/redact.mjs`, 'the one secret scrubber, shared rather than copied'],
    [`${ROUTER}/lib/cli.mjs`, 'one flag parser, so the dashboard cannot import it'],
    [`${ROUTER}/lib/telemetry/record.mjs`, 'the schema is data'],
    [`${ROUTER}/lib/telemetry/aggregate.mjs`, 'the one coverage fold'],
  ]
  const violations = []
  for (const [file, why] of pure) {
    const specs = GRAPH.builtins.get(file) ?? []
    if (specs.length > 0) violations.push(`${file} imports ${specs.join(' ')}: ${why}`)
  }
  assert.deepEqual(violations, [])

  // And the whole analytics layer, as a directory, because CLAUDE.md states it as a directory
  // property: "no `node:` import anywhere in the layer".
  const analyticsBuiltins = [...GRAPH.builtins]
    .filter(([f]) => f.startsWith(`${ROUTER}/lib/analytics/`))
    .map(([f, s]) => `${f}: ${s.join(' ')}`)
  assert.deepEqual(analyticsBuiltins, [])
})

test('only the two files allowed to spawn import node:child_process', () => {
  // Falls out of the exact map above, and is worth naming anyway: this is the property that keeps
  // a delegation path from gaining a shell.
  const spawners = [...GRAPH.builtins]
    .filter(([, specs]) => specs.includes('node:child_process'))
    .map(([f]) => f)
    .sort()
  assert.deepEqual(spawners, [
    `${ROUTER}/scripts/smoke-hook.mjs`,
    `${DASHBOARD}/scripts/collect.mjs`,
  ].sort())
})

/* ------------------------------------------------------------------------ cycles */

test('the import graph is acyclic, and names the cycle when it is not', () => {
  // Nothing in this repository detected a cycle before this test. A cycle is not a style problem:
  // telemetry -> analytics -> telemetry would put a reporting concern inside the module a
  // PreToolUse hook writes through, and analytics.isolation.test.mjs:410 bans exactly that ONE pair
  // by name. This bans the general case, including a three-hop cycle nobody thought to name.
  //
  // It is the complement of the rank rule: the only cycle the rank rule can permit is one built
  // entirely from same-rank, same-module edges, which is precisely what this finds.
  const WHITE = 0
  const GREY = 1
  const BLACK = 2
  const colour = new Map(Object.keys(ALL).map((f) => [f, WHITE]))
  const cycles = []

  for (const root of [...colour.keys()].sort()) {
    if (colour.get(root) !== WHITE) continue
    colour.set(root, GREY)
    const stack = [{ node: root, next: 0 }]
    while (stack.length > 0) {
      const top = stack[stack.length - 1]
      const kids = BY_SOURCE.get(top.node) ?? []
      if (top.next >= kids.length) {
        colour.set(top.node, BLACK)
        stack.pop()
        continue
      }
      const child = kids[top.next]
      top.next += 1
      if (!colour.has(child)) continue
      if (colour.get(child) === GREY) {
        const at = stack.findIndex((f) => f.node === child)
        cycles.push([...stack.slice(at).map((f) => f.node), child].join(' -> '))
        continue
      }
      if (colour.get(child) === WHITE) {
        colour.set(child, GREY)
        stack.push({ node: child, next: 0 })
      }
    }
  }
  assert.deepEqual(cycles, [], 'an import cycle')
})

/* ------------------------------------------------------------- the scanner itself */

test('the scanner finds every import form, proved against planted source', () => {
  // The fixture IS the test, because scanImports() takes text rather than a path — no mkdtemp, no
  // cleanup. The last four cases are the ones that made a strip-comments-then-regex first draft
  // produce false positives, and all three live in this repository.
  const planted = [
    "import a from './a.mjs'",
    'import {\n  b,\n  c as d,\n} from \'./b.mjs\'', // the form telemetry.isolation cannot see
    "export { e } from './c.mjs'", // the form evals/gates.mjs cannot see
    "export * from './d.mjs'",
    "import './e.mjs'",
    'const f = await import("./f.mjs")',
    "const g = require('./g.mjs')",
    "const KEYWORDS = ['import', 'imports', 'from', 'export']", // evaluators.mjs
    'const s = "from \'./nope.mjs\'"', // evals.determinism.test.mjs
    'const planted = "const a = await import(\'node:child_process\')"', // evals.gates.test.mjs
    "const RE = /from '([^']+)'/g",
    '// import z from "./comment.mjs"',
    '/* import y from "./block.mjs" */',
  ].join('\n')
  const { specs, computed } = scanImports(planted)
  assert.deepEqual(
    specs.sort(),
    ['./a.mjs', './b.mjs', './c.mjs', './d.mjs', './e.mjs', './f.mjs', './g.mjs'],
  )
  assert.deepEqual(computed, [])
})

test('the scanner reports a built-up specifier instead of losing it', () => {
  // The failure mode that matters most: an edge the graph cannot resolve must be LOUD. A template
  // with a substitution anywhere else in the file is not an edge and must stay quiet.
  assert.equal(scanImports('await import(`./${name}.mjs`)').computed.length, 1)
  assert.equal(scanImports('await import(someVariable)').computed.length, 1)
  assert.equal(scanImports('require(nameOf(x))').computed.length, 1)
  assert.deepEqual(scanImports('log(`reading ${dir}/x.mjs`)').computed, [])
  assert.deepEqual(scanImports("import('./ok.mjs')").computed, [])
})

test('the scanner is a strict superset of the four bodies it replaces', () => {
  // The claim that justifies this helper existing. Re-derived here over the real tree rather than
  // asserted in a comment, so it cannot quietly stop being true. The four bodies are reproduced
  // verbatim from their call sites; if one is edited there and not here, the superset check still
  // holds — it is the DIRECTION of the claim that matters, not the copies.
  const strip = (src) =>
    src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:])\/\/[^\n]*/g, '$1')
  const bodyA = (s) => {
    const o = []
    for (const m of s.matchAll(/(?:^|\n)\s*(?:import|export)\s[^'"]*from\s*['"]([^'"]+)['"]/g)) o.push(m[1])
    for (const m of s.matchAll(/(?:^|\n)\s*import\s*['"]([^'"]+)['"]/g)) o.push(m[1])
    for (const m of s.matchAll(/import\(\s*['"]([^'"]+)['"]\s*\)/g)) o.push(m[1])
    for (const m of s.matchAll(/require\(\s*['"]([^'"]+)['"]\s*\)/g)) o.push(m[1])
    return o
  }
  const bodyB = (s) =>
    [...s.matchAll(/(?:^|\n)\s*(?:import|export)[^\n]*?from\s+'([^']+)'/g)].map((m) => m[1])
  const bodyC = (s) => [...s.matchAll(/from\s+'([^']+)'/g)].map((m) => m[1])
  const bodyD = (s) => {
    const o = []
    for (const m of s.matchAll(/(?:^|\n)\s*import\s[^'"]*['"]([^'"]+)['"]/g)) o.push(m[1])
    for (const m of s.matchAll(/import\(\s*['"]([^'"]+)['"]\s*\)/g)) o.push(m[1])
    for (const m of s.matchAll(/require\(\s*['"]([^'"]+)['"]\s*\)/g)) o.push(m[1])
    return o
  }

  const missing = []
  for (const rel of filesOnDisk()) {
    const raw = read(rel)
    const mine = new Set(scanImports(raw).specs)
    const stripped = strip(raw)
    for (const [name, body] of [['A', bodyA], ['B', bodyB], ['C', bodyC], ['D', bodyD]]) {
      for (const spec of body(stripped)) {
        if (mine.has(spec)) continue
        // Only a REAL edge counts. A body that matches inside a string literal finds specifiers
        // that do not resolve, and failing to reproduce those is the improvement, not a regression.
        const real =
          spec.startsWith('node:') ||
          fs.existsSync(path.resolve(path.dirname(path.join(ROOT, rel)), spec))
        if (real) missing.push(`body ${name}: ${rel} -> ${spec}`)
      }
    }
  }
  assert.deepEqual(missing, [], 'an existing regex found a real edge the shared scanner missed')
})

test('the number of local import scanners under test/ has not grown', () => {
  // This does NOT refactor the eight copies that exist. It freezes the count, so that the next
  // person to need an import scan reaches for test/helpers/imports.mjs instead of pasting a ninth
  // regex — and so that the two weak bodies stay a known, bounded debt rather than a growing one.
  //
  // The count is 8: four copies of one body (governance/analytics/evals/dashboard isolation), two
  // of another (telemetry.isolation, hook.security), plus routing.capability and evals/gates.mjs.
  // Both definition forms, because they are both in use: a `function` declaration in six files
  // and an arrow in routing.capability.test.mjs. A pattern for only one of them reports 7 and
  // looks like a passing count.
  const DEFINITION = /(?:function\s+|const\s+)(importsOf|scanForCapability)\s*(?:\(|=)/g
  const localScanners = []
  for (const p of walk(TEST_DIR)) {
    const rel = slash(path.relative(ROOT, p))
    if (rel === 'test/helpers/imports.mjs' || rel === 'test/architecture.graph.test.mjs') continue
    const src = fs.readFileSync(p, 'utf8')
    for (const m of src.matchAll(DEFINITION)) {
      localScanners.push(`${rel}: ${m[1]}`)
    }
  }
  assert.equal(
    localScanners.length,
    8,
    `local import scanners: ${localScanners.join(', ')} — use test/helpers/imports.mjs`,
  )
})
