/**
 * VERIFYING A SUMMARY AGAINST THE FILE, and refusing to substitute one that does not check out.
 *
 * THE FAILURE THIS CLOSES. A worker's answer REPLACES the file in Claude's context. If the answer
 * is wrong, Claude's context is wrong and everything after it inherits the error — and the
 * developer cannot see it, because the file never reached Claude. A delegation that returns a
 * confident fabrication is worse than no delegation at all.
 *
 * WHY IT IS CHECKABLE WITHOUT A JUDGE MODEL: we still have the file. The answer makes mechanical
 * claims about it — this symbol is on that line, this literal appears, this name exists — and every
 * one is exactly checkable against the bytes.
 *
 * THE ASYMMETRY, which is what justifies discarding on a single failed claim. A false positive
 * throws away a good summary and the developer gets the ordinary `Read` they would have had
 * anyway: one wasted worker call. A false negative puts an invented line number into Claude's
 * context. Those are not comparable, so the default favours the cheap mistake.
 *
 * EVERY FIXTURE BELOW IS A REAL ANSWER from Ollama / mistral:latest at temperature 0, except the
 * fabrication. That matters: a verifier tuned against invented examples passes its own tests and
 * then flags real output. The first draft of the extractor did exactly that — see the
 * nearest-span test.
 */

import assert from 'node:assert/strict'
import test from 'node:test'

import {
  LINE_TOLERANCE,
  VERIFY_VERDICTS,
  describeVerification,
  verifySummary,
} from '../plugins/model-router/lib/verify/summary.mjs'

/** The file the real answers below were produced from, trimmed to what they reference. */
const FILE = [
  '/**',
  ' * A synthetic but realistic TypeScript module used as a delegation corpus.',
  ' *',
  ' * Generated by test/fixtures/corpus/README.md instructions: it only has to be bigger than',
  ' * routing.bulkRead.minBytes (12000) and longer than minLines (350) so the gate delegates it.',
  ' */',
  '',
  'export interface Entity { id: string; createdAt: Date; updatedAt: Date }',
  '',
  '/** Domain record number 1, with the audit fields every table in this schema carries. */',
  'export interface Record1 extends Entity {',
  '  name: string',
  '  slug: string',
  '  ordinal: number',
  '  enabled: boolean',
  '  metadata: Record<string, string | number | null>',
  '}',
  '',
  'export function normalizeRecord1(input: Partial<Record1>): Record1 {',
  '  if (!input.id) throw new TypeError("Record1 requires an id")',
  '  return {',
  '    id: input.id,',
  '  }',
  '}',
].join('\n')

const files = [{ path: 'corpus/tiny-real.ts', content: FILE }]
const verify = (answer) => verifySummary({ answer, files })

/**
 * A REAL answer, verbatim, from the line-numbered prompt. Its three line claims — `Entity` 8,
 * `Record1` 11, `normalizeRecord1` 19 — are all exact against the file above.
 */
const REAL_GOOD = [
  'This TypeScript file, located at `corpus/tiny-real.ts`, serves as a synthetic yet realistic',
  'TypeScript module for testing purposes.',
  '',
  'The file defines an interface `Entity` on line 8, which has properties `id`, `createdAt`, and',
  '`updatedAt` of types `string`, `Date`, and `Date` respectively.',
  '',
  'On line 11, it defines an interface `Record1` that extends `Entity`, adding properties `name`,',
  '`slug`, `ordinal`, `enabled`, and `metadata` of types `string`, `string`, `number`, `boolean`,',
  'and `Record<string, string | number | null>` respectively.',
  '',
  'On line 19, it defines a function `normalizeRecord1` that takes a `Partial<Record1>` as input',
  'and returns a fully populated `Record1` object.',
].join('\n')

/** A REAL answer from the un-numbered prompt: the worker simply omitted every line reference. */
const REAL_NO_LINES = [
  'This TypeScript file, located at `corpus/tiny-real.ts`, serves as a synthetic module.',
  'The file defines an interface `Entity` with properties `id`, `createdAt`, and `updatedAt`.',
  'The file contains a function `normalizeRecord1` that takes a `Partial<Record1>` as input.',
].join('\n')

/** A fabrication with the shape of a good summary: wrong lines, invented symbols, invented literal. */
const FABRICATED = [
  'This file defines an interface `Entity` on line 142.',
  'On line 203 it declares `getUserById`, which queries the database.',
  'It throws `"user not found in registry"` when the lookup fails.',
  'The `UserRepository` class on line 310 wraps all of this.',
].join('\n')

/* ------------------------------------------------------------------ the contract */

test('the verdict vocabulary is closed, and not_checkable is not a pass', () => {
  assert.deepEqual([...VERIFY_VERDICTS], ['verified', 'suspect', 'not_checkable'])
  // An answer that makes no mechanical claim is not verified. Calling it `verified` would let a
  // worker pass by saying nothing checkable at all.
  const r = verify('This file is quite long and does several things.')
  assert.equal(r.verdict, 'not_checkable')
  assert.equal(r.checkable, false)
})

test('the result is frozen, so a caller cannot launder a verdict', () => {
  const r = verify(FABRICATED)
  assert.ok(Object.isFrozen(r))
  assert.ok(Object.isFrozen(r.lineClaims))
})

/* ----------------------------------------------- a real answer must not be flagged */

test('a REAL good answer verifies, with all three of its line claims confirmed', () => {
  const r = verify(REAL_GOOD)
  assert.equal(r.verdict, 'verified', `expected verified, got ${r.reason}`)
  assert.equal(r.lineClaims.total, 3, 'three claims, not one per backticked token')
  assert.equal(r.lineClaims.verified, 3)
  assert.equal(r.lineClaims.wrong, 0)
  assert.equal(r.identifiers.ungrounded, 0, 'every name it quoted is in the file')
})

test('ONE claim per line reference: the nearest code span, not every token in the sentence', () => {
  // THE BUG THAT A REAL ANSWER CAUGHT, and the reason this file uses real answers. The first
  // extractor paired "On line 11" with all nine backticked tokens in its sentence — `Record1`,
  // `Entity`, and the seven property names — manufacturing eight claims the worker never made.
  // The properties really are on lines 12 to 16, so a correct summary was reported as suspect.
  const r = verify(REAL_GOOD)
  assert.equal(r.lineClaims.total, 3)

  // Both phrasings a real worker uses, checked separately so a regression names which one broke.
  const after = verify('It defines an interface `Record1` on line 11.')
  assert.equal(after.lineClaims.total, 1)
  assert.equal(after.lineClaims.verified, 1)

  const before = verify('On line 11, it defines an interface `Record1` with several properties.')
  assert.equal(before.lineClaims.total, 1)
  assert.equal(before.lineClaims.verified, 1, 'the subject sits next to the number in both orders')
})

test('an answer with no line claims is judged on what it DID claim', () => {
  // The shipped prompt produced this for months. Every name it quotes is real, so it verifies —
  // but `lineClaims.total: 0` is on the record, which is how an operator sees that the evidence
  // was thinner than it looks.
  const r = verify(REAL_NO_LINES)
  assert.equal(r.verdict, 'verified')
  assert.equal(r.lineClaims.total, 0)
  assert.ok(r.identifiers.total > 0, 'identifiers were still checked')
})

/* ----------------------------------------------------- a fabrication must be caught */

test('a fabrication is suspect, and all three checks say so independently', () => {
  const r = verify(FABRICATED)
  assert.equal(r.verdict, 'suspect')
  assert.match(r.reason, /line_claims_wrong:3/)
  assert.match(r.reason, /literals_absent:1/)
  assert.match(r.reason, /identifiers_absent:/)
})

test('a wrong line number says where the symbol actually is, which is what makes it actionable', () => {
  const r = verify('The interface `Entity` is declared on line 142.')
  assert.equal(r.verdict, 'suspect')
  assert.equal(r.lineClaims.wrong, 1)
  assert.match(r.lineClaims.examples[0], /Entity claimed on line 142/)
  assert.match(r.lineClaims.examples[0], /actually on 8/, 'and names the real line')
})

test('a symbol absent from the file is reported as absent, not as misplaced', () => {
  // Two different failures. A wrong line is a counting mistake; a missing symbol is an invention,
  // and conflating them would hide the worse one.
  const r = verify('On line 203 it declares `getUserById`.')
  assert.equal(r.verdict, 'suspect')
  assert.match(r.lineClaims.examples[0], /absent from the file/)
})

test('an invented string literal is enough on its own', () => {
  // The task tells the worker to preserve literals exactly as written, so a quoted literal that
  // is not in the file was invented. No benign explanation, so no ratio and no threshold.
  const r = verify('It throws `"user not found in registry"` on failure.')
  assert.equal(r.verdict, 'suspect')
  assert.equal(r.literals.ungrounded, 1)
  assert.deepEqual([...r.literals.examples], ['user not found in registry'])
})

test('a literal that IS in the file is confirmed', () => {
  const r = verify('It throws `"Record1 requires an id"` when the input has no id.')
  assert.equal(r.literals.ungrounded, 0)
  assert.equal(r.literals.grounded, 1)
  assert.equal(r.verdict, 'verified')
})

/* -------------------------------------------------------- the tolerances, and why */

test('a line claim within the tolerance is confirmed, because a doc comment is a fair answer', () => {
  // `Record1` is declared on line 11 and its doc comment is on line 10. Both are defensible
  // answers to "what line is it on", and fabrication misses by tens or hundreds — so a window of
  // two costs nothing in detection and removes an argument.
  assert.equal(LINE_TOLERANCE, 2)
  // `ordinal` occurs exactly once, on line 14, so the window is unambiguous.
  assert.equal(verify('`ordinal` is on line 14.').lineClaims.verified, 1, 'exact')
  assert.equal(verify('`ordinal` is on line 12.').lineClaims.verified, 1, 'two above')
  assert.equal(verify('`ordinal` is on line 16.').lineClaims.verified, 1, 'two below')
  assert.equal(verify('`ordinal` is on line 17.').lineClaims.wrong, 1, 'three out is wrong')
})

test('LIMITATION: it confirms a symbol APPEARS near the line, not that it is DECLARED there', () => {
  // Stated as a test rather than left for somebody to discover. `Record1` occurs on lines 11, 19
  // and 20 — its declaration, a signature, and a string literal — so a claim of line 19 or 20
  // verifies even though the DECLARATION is on 11. Substring matching cannot tell those apart
  // without parsing TypeScript, which this module deliberately does not do.
  //
  // The check is still worth having: a fabrication cites a line nowhere near any occurrence (142,
  // 203, 310 in the fixture above) and fails. What is weakened is detection for a symbol that
  // appears throughout a file, and the honest description of the check is "the symbol is at or
  // near the line claimed", which is what the caveat text says too.
  assert.equal(verify('`Record1` is declared on line 11.').lineClaims.verified, 1, 'true')
  assert.equal(verify('`Record1` is declared on line 19.').lineClaims.verified, 1, 'ALSO passes')
  // And the failure mode that matters is unaffected.
  assert.equal(verify('`Record1` is declared on line 300.').lineClaims.wrong, 1)
})

test('identifiers are judged by ratio, because a long answer may name an outside type', () => {
  // A wrong line or an invented literal triggers on its own; identifiers do not, because a summary
  // legitimately mentions a library type or a word from the task. The ratio is what separates
  // "mentioned something outside the file" from "made the file up".
  const oneStray = verify(
    'The file defines `Entity`, `Record1`, `normalizeRecord1`, `metadata`, `ordinal` and uses `SomeLibraryType`.',
  )
  assert.equal(oneStray.verdict, 'verified', 'one stray name in six is not a fabrication')
  assert.ok(oneStray.identifiers.ungrounded >= 1, 'but it is still counted')

  const mostlyStray = verify('It defines `alpha`, `bravo`, `charlie`, `delta` and `echo`.')
  assert.equal(mostlyStray.verdict, 'suspect')
})

test('the identifier lexicon includes the file PATH, which the worker was also given', () => {
  // Found against a real answer: the worker quotes the path back, and without the path in the
  // lexicon its segments were flagged as invented.
  const r = verify('The file `corpus/tiny-real.ts` defines `Entity` on line 8.')
  assert.equal(r.identifiers.ungrounded, 0)
  assert.equal(r.verdict, 'verified')
})

test('only BACKTICKED identifiers are checked, so prose cannot produce a false positive', () => {
  // The eval framework's advisory grounding check scans prose and documents its own
  // false-positive rate as roughly one per five cases, from casing drift and composition.
  // Backticks are explicit: the worker put them there to mark a name it is quoting.
  const r = verify(
    'This module has a clear structure and a sensible purpose, declaring several domain records ' +
      'with audit fields and a normalization helper for each.',
  )
  assert.equal(r.identifiers.total, 0, 'prose words are not identifier claims')
  assert.equal(r.verdict, 'not_checkable')
})

/* --------------------------------------------------------- fail-open on bad input */

test('missing or empty input is not_checkable rather than a throw or a pass', () => {
  for (const args of [
    {},
    { answer: '', files },
    { answer: REAL_GOOD, files: [] },
    { answer: REAL_GOOD, files: null },
    { answer: null, files },
    { answer: REAL_GOOD, files: [{ path: 'x', content: '' }] },
  ]) {
    const r = verifySummary(args)
    assert.equal(r.verdict, 'not_checkable', JSON.stringify(Object.keys(args)))
    assert.equal(r.checkable, false)
  }
})

/* ----------------------------------------------------------------- the caveat text */

test('the caveat names what failed, because Claude is the one consumer that can act on it', () => {
  // Claude can re-read the file. So a caveat saying "this may be unreliable" is useless and one
  // naming the failed claims is actionable.
  const caveat = describeVerification(verify(FABRICATED))
  assert.match(caveat, /3 of 3 line references could not be confirmed/)
  assert.match(caveat, /1 quoted literal/)
  assert.match(caveat, /re-read the file with offset and limit/)
})

test('a verified or uncheckable answer gets no caveat at all', () => {
  // A caveat that is always present is a caveat nobody reads.
  assert.equal(describeVerification(verify(REAL_GOOD)), null)
  assert.equal(describeVerification(verify('Nothing checkable here.')), null)
  assert.equal(describeVerification(null), null)
})
