#!/usr/bin/env node
/**
 * ONE release version, propagated. The root `package.json` `version` is the source; everything
 * else is derived from it and regenerated, exactly as `lib/config.schema.json` is derived from
 * `SPEC`. CI runs this and then `git diff --exit-code`, so a half-applied bump fails the build.
 *
 * Why generate rather than read at runtime. Two of the places the version appears cannot read a
 * manifest at all:
 *
 *   - `lib/telemetry/record.mjs` is imported by the PreToolUse hook. A `readFileSync` at module
 *     init would add a filesystem read to every gated Read, and JSON import attributes still
 *     print an experimental warning on some Node 22 lines — onto the channel Claude Code parses.
 *   - Nothing under `plugins/router-dashboard/lib/` imports a node builtin, and a test pins that
 *     by inspecting import specifiers. The renderer physically cannot open its own manifest.
 *
 * So both get a generated zero-import module instead, and the hot path pays nothing.
 *
 * The RELEASE version is not a contract version. `SCHEMA_VERSION`, `CALC_VERSION`,
 * `CONFIG_VERSION`, `POLICY_VERSION`, `PROMPT_VERSION`, `INTENT_PROMPT_VERSION`,
 * `ANALYTICS_CONTRACT_VERSION` and `pricingVersion` each answer "can you still read my data" and
 * bump on their own schedule. This script must never touch them. Cross-plugin compatibility is
 * negotiated through `DASHBOARD_CONTRACT_VERSIONS`, never inferred from a release number.
 *
 * This file lives in the repo root `scripts/`, not under a plugin: `marketplace.json` ships only
 * `./plugins/<name>`, so a root script is never installed into a user's plugin tree, and it would
 * otherwise have to write across the plugin boundary into `router-dashboard`.
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

export const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

const SEMVER = /^\d+\.\d+\.\d+$/

/**
 * Each row names its own source key, so letting the two plugins diverge later is a data change
 * rather than a rewrite. Every row currently reads the one `version`.
 */
export const JSON_TARGETS = Object.freeze([
  { file: '.claude-plugin/marketplace.json', scope: { kind: 'top' }, source: 'version' },
  {
    file: '.claude-plugin/marketplace.json',
    scope: { kind: 'entry', name: 'model-router' },
    source: 'version',
  },
  {
    file: '.claude-plugin/marketplace.json',
    scope: { kind: 'entry', name: 'router-dashboard' },
    source: 'version',
  },
  {
    file: 'plugins/model-router/.claude-plugin/plugin.json',
    scope: { kind: 'top' },
    source: 'version',
  },
  {
    file: 'plugins/router-dashboard/.claude-plugin/plugin.json',
    scope: { kind: 'top' },
    source: 'version',
  },
])

export const MODULE_TARGETS = Object.freeze([
  { file: 'plugins/model-router/lib/version.mjs', constName: 'ROUTER_VERSION', source: 'version' },
  {
    file: 'plugins/router-dashboard/lib/version.mjs',
    constName: 'DASHBOARD_VERSION',
    source: 'version',
  },
])

/** The source of truth. Throws rather than guessing: a bad version must not be propagated. */
export function readSourceVersion(root = REPO_ROOT) {
  const raw = fs.readFileSync(path.join(root, 'package.json'), 'utf8')
  const version = JSON.parse(raw).version
  if (typeof version !== 'string' || !SEMVER.test(version)) {
    throw new Error(
      `package.json version must be a plain semver triple, got ${JSON.stringify(version)}`,
    )
  }
  return version
}

/** The exact bytes of a generated version module. Tests call this to detect staleness. */
export function renderVersionModule({ constName, version }) {
  return [
    '/** GENERATED by scripts/sync-version.mjs from package.json `version`. Do not edit. */',
    `export const ${constName} = '${version}'`,
    '',
  ].join('\n')
}

/**
 * Replace every character inside a JSON string literal with a space, preserving length and
 * offsets. Brace matching over the result cannot be fooled by a brace inside a string.
 */
export function maskStrings(text) {
  const out = text.split('')
  let inString = false
  let escaped = false
  for (let i = 0; i < text.length; i++) {
    const ch = text[i]
    if (inString) {
      out[i] = ' '
      if (escaped) escaped = false
      else if (ch === '\\') escaped = true
      else if (ch === '"') {
        out[i] = '"'
        inString = false
      }
    } else if (ch === '"') {
      inString = true
    }
  }
  return out.join('')
}

/**
 * The `[start, end)` span of the object literal containing `needle`. Used to bound a rewrite to
 * one plugin entry, so a `"version"` elsewhere in the document can never be hit by mistake.
 */
export function regionOfObject(text, needle) {
  const at = text.indexOf(needle)
  if (at === -1) throw new Error(`could not locate ${JSON.stringify(needle)}`)
  if (text.indexOf(needle, at + 1) !== -1) {
    throw new Error(`${JSON.stringify(needle)} appears more than once; the region is ambiguous`)
  }
  const masked = maskStrings(text)
  let depth = 0
  let start = -1
  for (let i = at; i >= 0; i--) {
    if (masked[i] === '}') depth++
    else if (masked[i] === '{') {
      if (depth === 0) {
        start = i
        break
      }
      depth--
    }
  }
  if (start === -1) throw new Error(`no opening brace found before ${JSON.stringify(needle)}`)
  depth = 0
  for (let i = start; i < text.length; i++) {
    if (masked[i] === '{') depth++
    else if (masked[i] === '}') {
      depth--
      if (depth === 0) return { start, end: i + 1 }
    }
  }
  throw new Error(`unbalanced braces after ${JSON.stringify(needle)}`)
}

/**
 * Splice a string field's value inside `[from, to)`, touching only the bytes between its quotes.
 *
 * Deliberately NOT a JSON.parse/stringify round trip. These manifests are hand-formatted and
 * inconsistently so on purpose (`"author": { "name": "..." }` inline in one file, expanded in
 * another), and a round trip would flatten all of it and rewrite every line ending, making the
 * CI diff gate fail by platform rather than by regression.
 */
export function setJsonStringField(text, key, value, { from = 0, to = text.length } = {}) {
  const slice = text.slice(from, to)
  const re = new RegExp(`"${key}"\\s*:\\s*"(?:[^"\\\\]|\\\\.)*"`, 'g')
  const hits = slice.match(re) ?? []
  if (hits.length !== 1) {
    throw new Error(`expected exactly one "${key}" in the bounded region, found ${hits.length}`)
  }
  const at = from + slice.indexOf(hits[0])
  return text.slice(0, at) + `"${key}": ${JSON.stringify(value)}` + text.slice(at + hits[0].length)
}

function boundsFor(text, scope) {
  if (scope.kind === 'top') {
    // Stop before the plugins array so a top-level rewrite can never reach an entry's field.
    // Located in the raw text, not the masked copy: masking blanks key names too, so a search
    // for `"plugins"` over the mask finds nothing and the bound would silently fall open to the
    // whole document — which is exactly how a top-level rewrite would reach all three fields.
    const pluginsAt = text.indexOf('"plugins"')
    if (pluginsAt !== text.lastIndexOf('"plugins"')) {
      throw new Error('"plugins" appears more than once; the top-level region is ambiguous')
    }
    return { from: 0, to: pluginsAt === -1 ? text.length : pluginsAt }
  }
  const region = regionOfObject(text, `"name": ${JSON.stringify(scope.name)}`)
  return { from: region.start, to: region.end }
}

/** Expected object after the splice: the original, with only the intended version replaced. */
function expectedObject(original, scope, version) {
  const next = JSON.parse(JSON.stringify(original))
  if (scope.kind === 'top') next.version = version
  else {
    const entry = (next.plugins ?? []).find((p) => p?.name === scope.name)
    if (!entry) throw new Error(`no plugins[] entry named ${scope.name}`)
    entry.version = version
  }
  return next
}

/**
 * Propagate the source version. Returns one row per file considered.
 *
 * @param {object}  [opts]
 * @param {boolean} [opts.check]   report drift, write nothing
 * @param {string}  [opts.expect]  assert the source version first (the release workflow uses this)
 */
export function syncVersion({ root = REPO_ROOT, check = false, expect = null } = {}) {
  const version = readSourceVersion(root)
  if (expect !== null && expect !== version) {
    throw new Error(`expected version ${expect}, but package.json says ${version}`)
  }

  const pending = new Map()
  const read = (rel) => {
    if (!pending.has(rel)) pending.set(rel, fs.readFileSync(path.join(root, rel), 'utf8'))
    return pending.get(rel)
  }

  for (const target of JSON_TARGETS) {
    const before = read(target.file)
    const parsedBefore = JSON.parse(before)
    const bounds = boundsFor(before, target.scope)
    const after = setJsonStringField(before, 'version', version, bounds)
    // Verify before trusting the splice: the document must differ in exactly the intended way.
    const want = expectedObject(parsedBefore, target.scope, version)
    if (JSON.stringify(JSON.parse(after)) !== JSON.stringify(want)) {
      throw new Error(`the splice changed ${target.file} unexpectedly; nothing was written`)
    }
    pending.set(target.file, after)
  }

  for (const target of MODULE_TARGETS) {
    pending.set(target.file, renderVersionModule({ constName: target.constName, version }))
  }

  const results = []
  for (const [rel, next] of pending) {
    const abs = path.join(root, rel)
    const prev = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null
    const changed = prev !== next
    if (changed && !check) fs.writeFileSync(abs, next)
    results.push({ file: rel, changed })
  }
  return { version, results }
}

function main(argv) {
  const check = argv.includes('--check')
  const at = argv.indexOf('--expect')
  const expect = at === -1 ? null : (argv[at + 1] ?? null)
  if (at !== -1 && (expect === null || expect.startsWith('--'))) {
    console.error('--expect needs a version')
    return 2
  }

  let result
  try {
    result = syncVersion({ check, expect })
  } catch (err) {
    console.error(String(err?.message ?? err))
    return 1
  }

  const drifted = result.results.filter((r) => r.changed)
  if (drifted.length === 0) {
    console.log(`already up to date at ${result.version}`)
    return 0
  }
  for (const r of drifted) console.log(`${check ? 'stale' : 'updated'} ${r.file}`)
  if (check) {
    console.error(
      `${drifted.length} file(s) disagree with package.json ${result.version} — run: npm run sync:version`,
    )
    return 1
  }
  return 0
}

if (process.argv[1] && path.resolve(process.argv[1]).endsWith('sync-version.mjs')) {
  process.exit(main(process.argv.slice(2)))
}
