/**
 * A synthetic but realistic TypeScript module used as a delegation corpus.
 *
 * Generated by test/fixtures/corpus/README.md instructions: it only has to be bigger than
 * routing.bulkRead.minBytes (12000) and longer than minLines (350) so the gate delegates it.
 */

export interface Entity { id: string; createdAt: Date; updatedAt: Date }

/** Domain record number 1, with the audit fields every table in this schema carries. */
export interface Record1 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord1(input: Partial<Record1>): Record1 {
  if (!input.id) throw new TypeError("Record1 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 2, with the audit fields every table in this schema carries. */
export interface Record2 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord2(input: Partial<Record2>): Record2 {
  if (!input.id) throw new TypeError("Record2 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 3, with the audit fields every table in this schema carries. */
export interface Record3 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord3(input: Partial<Record3>): Record3 {
  if (!input.id) throw new TypeError("Record3 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 4, with the audit fields every table in this schema carries. */
export interface Record4 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord4(input: Partial<Record4>): Record4 {
  if (!input.id) throw new TypeError("Record4 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 5, with the audit fields every table in this schema carries. */
export interface Record5 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord5(input: Partial<Record5>): Record5 {
  if (!input.id) throw new TypeError("Record5 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 6, with the audit fields every table in this schema carries. */
export interface Record6 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord6(input: Partial<Record6>): Record6 {
  if (!input.id) throw new TypeError("Record6 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 7, with the audit fields every table in this schema carries. */
export interface Record7 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord7(input: Partial<Record7>): Record7 {
  if (!input.id) throw new TypeError("Record7 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 8, with the audit fields every table in this schema carries. */
export interface Record8 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord8(input: Partial<Record8>): Record8 {
  if (!input.id) throw new TypeError("Record8 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 9, with the audit fields every table in this schema carries. */
export interface Record9 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord9(input: Partial<Record9>): Record9 {
  if (!input.id) throw new TypeError("Record9 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 10, with the audit fields every table in this schema carries. */
export interface Record10 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord10(input: Partial<Record10>): Record10 {
  if (!input.id) throw new TypeError("Record10 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 11, with the audit fields every table in this schema carries. */
export interface Record11 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord11(input: Partial<Record11>): Record11 {
  if (!input.id) throw new TypeError("Record11 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 12, with the audit fields every table in this schema carries. */
export interface Record12 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord12(input: Partial<Record12>): Record12 {
  if (!input.id) throw new TypeError("Record12 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 13, with the audit fields every table in this schema carries. */
export interface Record13 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord13(input: Partial<Record13>): Record13 {
  if (!input.id) throw new TypeError("Record13 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 14, with the audit fields every table in this schema carries. */
export interface Record14 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord14(input: Partial<Record14>): Record14 {
  if (!input.id) throw new TypeError("Record14 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 15, with the audit fields every table in this schema carries. */
export interface Record15 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord15(input: Partial<Record15>): Record15 {
  if (!input.id) throw new TypeError("Record15 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 16, with the audit fields every table in this schema carries. */
export interface Record16 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord16(input: Partial<Record16>): Record16 {
  if (!input.id) throw new TypeError("Record16 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 17, with the audit fields every table in this schema carries. */
export interface Record17 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord17(input: Partial<Record17>): Record17 {
  if (!input.id) throw new TypeError("Record17 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 18, with the audit fields every table in this schema carries. */
export interface Record18 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord18(input: Partial<Record18>): Record18 {
  if (!input.id) throw new TypeError("Record18 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 19, with the audit fields every table in this schema carries. */
export interface Record19 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord19(input: Partial<Record19>): Record19 {
  if (!input.id) throw new TypeError("Record19 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 20, with the audit fields every table in this schema carries. */
export interface Record20 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord20(input: Partial<Record20>): Record20 {
  if (!input.id) throw new TypeError("Record20 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 21, with the audit fields every table in this schema carries. */
export interface Record21 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord21(input: Partial<Record21>): Record21 {
  if (!input.id) throw new TypeError("Record21 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 22, with the audit fields every table in this schema carries. */
export interface Record22 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord22(input: Partial<Record22>): Record22 {
  if (!input.id) throw new TypeError("Record22 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 23, with the audit fields every table in this schema carries. */
export interface Record23 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord23(input: Partial<Record23>): Record23 {
  if (!input.id) throw new TypeError("Record23 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 24, with the audit fields every table in this schema carries. */
export interface Record24 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord24(input: Partial<Record24>): Record24 {
  if (!input.id) throw new TypeError("Record24 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 25, with the audit fields every table in this schema carries. */
export interface Record25 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord25(input: Partial<Record25>): Record25 {
  if (!input.id) throw new TypeError("Record25 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 26, with the audit fields every table in this schema carries. */
export interface Record26 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord26(input: Partial<Record26>): Record26 {
  if (!input.id) throw new TypeError("Record26 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 27, with the audit fields every table in this schema carries. */
export interface Record27 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord27(input: Partial<Record27>): Record27 {
  if (!input.id) throw new TypeError("Record27 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 28, with the audit fields every table in this schema carries. */
export interface Record28 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord28(input: Partial<Record28>): Record28 {
  if (!input.id) throw new TypeError("Record28 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 29, with the audit fields every table in this schema carries. */
export interface Record29 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord29(input: Partial<Record29>): Record29 {
  if (!input.id) throw new TypeError("Record29 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 30, with the audit fields every table in this schema carries. */
export interface Record30 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord30(input: Partial<Record30>): Record30 {
  if (!input.id) throw new TypeError("Record30 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 31, with the audit fields every table in this schema carries. */
export interface Record31 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord31(input: Partial<Record31>): Record31 {
  if (!input.id) throw new TypeError("Record31 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 32, with the audit fields every table in this schema carries. */
export interface Record32 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord32(input: Partial<Record32>): Record32 {
  if (!input.id) throw new TypeError("Record32 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 33, with the audit fields every table in this schema carries. */
export interface Record33 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord33(input: Partial<Record33>): Record33 {
  if (!input.id) throw new TypeError("Record33 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 34, with the audit fields every table in this schema carries. */
export interface Record34 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord34(input: Partial<Record34>): Record34 {
  if (!input.id) throw new TypeError("Record34 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 35, with the audit fields every table in this schema carries. */
export interface Record35 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord35(input: Partial<Record35>): Record35 {
  if (!input.id) throw new TypeError("Record35 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 36, with the audit fields every table in this schema carries. */
export interface Record36 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord36(input: Partial<Record36>): Record36 {
  if (!input.id) throw new TypeError("Record36 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 37, with the audit fields every table in this schema carries. */
export interface Record37 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord37(input: Partial<Record37>): Record37 {
  if (!input.id) throw new TypeError("Record37 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 38, with the audit fields every table in this schema carries. */
export interface Record38 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord38(input: Partial<Record38>): Record38 {
  if (!input.id) throw new TypeError("Record38 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 39, with the audit fields every table in this schema carries. */
export interface Record39 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord39(input: Partial<Record39>): Record39 {
  if (!input.id) throw new TypeError("Record39 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 40, with the audit fields every table in this schema carries. */
export interface Record40 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord40(input: Partial<Record40>): Record40 {
  if (!input.id) throw new TypeError("Record40 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 41, with the audit fields every table in this schema carries. */
export interface Record41 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord41(input: Partial<Record41>): Record41 {
  if (!input.id) throw new TypeError("Record41 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 42, with the audit fields every table in this schema carries. */
export interface Record42 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord42(input: Partial<Record42>): Record42 {
  if (!input.id) throw new TypeError("Record42 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 43, with the audit fields every table in this schema carries. */
export interface Record43 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord43(input: Partial<Record43>): Record43 {
  if (!input.id) throw new TypeError("Record43 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 44, with the audit fields every table in this schema carries. */
export interface Record44 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord44(input: Partial<Record44>): Record44 {
  if (!input.id) throw new TypeError("Record44 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 45, with the audit fields every table in this schema carries. */
export interface Record45 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord45(input: Partial<Record45>): Record45 {
  if (!input.id) throw new TypeError("Record45 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 46, with the audit fields every table in this schema carries. */
export interface Record46 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord46(input: Partial<Record46>): Record46 {
  if (!input.id) throw new TypeError("Record46 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 47, with the audit fields every table in this schema carries. */
export interface Record47 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord47(input: Partial<Record47>): Record47 {
  if (!input.id) throw new TypeError("Record47 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 48, with the audit fields every table in this schema carries. */
export interface Record48 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord48(input: Partial<Record48>): Record48 {
  if (!input.id) throw new TypeError("Record48 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 49, with the audit fields every table in this schema carries. */
export interface Record49 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord49(input: Partial<Record49>): Record49 {
  if (!input.id) throw new TypeError("Record49 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 50, with the audit fields every table in this schema carries. */
export interface Record50 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord50(input: Partial<Record50>): Record50 {
  if (!input.id) throw new TypeError("Record50 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 51, with the audit fields every table in this schema carries. */
export interface Record51 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord51(input: Partial<Record51>): Record51 {
  if (!input.id) throw new TypeError("Record51 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 52, with the audit fields every table in this schema carries. */
export interface Record52 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord52(input: Partial<Record52>): Record52 {
  if (!input.id) throw new TypeError("Record52 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 53, with the audit fields every table in this schema carries. */
export interface Record53 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord53(input: Partial<Record53>): Record53 {
  if (!input.id) throw new TypeError("Record53 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 54, with the audit fields every table in this schema carries. */
export interface Record54 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord54(input: Partial<Record54>): Record54 {
  if (!input.id) throw new TypeError("Record54 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 55, with the audit fields every table in this schema carries. */
export interface Record55 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord55(input: Partial<Record55>): Record55 {
  if (!input.id) throw new TypeError("Record55 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 56, with the audit fields every table in this schema carries. */
export interface Record56 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord56(input: Partial<Record56>): Record56 {
  if (!input.id) throw new TypeError("Record56 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 57, with the audit fields every table in this schema carries. */
export interface Record57 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord57(input: Partial<Record57>): Record57 {
  if (!input.id) throw new TypeError("Record57 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 58, with the audit fields every table in this schema carries. */
export interface Record58 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord58(input: Partial<Record58>): Record58 {
  if (!input.id) throw new TypeError("Record58 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 59, with the audit fields every table in this schema carries. */
export interface Record59 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord59(input: Partial<Record59>): Record59 {
  if (!input.id) throw new TypeError("Record59 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 60, with the audit fields every table in this schema carries. */
export interface Record60 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord60(input: Partial<Record60>): Record60 {
  if (!input.id) throw new TypeError("Record60 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}
