/**
 * A synthetic but realistic TypeScript module used as a delegation corpus.
 *
 * Generated by test/fixtures/corpus/README.md instructions: it only has to be bigger than
 * routing.bulkRead.minBytes (12000) and longer than minLines (350) so the gate delegates it.
 */

export interface Entity { id: string; createdAt: Date; updatedAt: Date }

/** Domain record number 1, with the audit fields every table in this schema carries. */
export interface Record1 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord1(input: Partial<Record1>): Record1 {
  if (!input.id) throw new TypeError("Record1 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 2, with the audit fields every table in this schema carries. */
export interface Record2 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord2(input: Partial<Record2>): Record2 {
  if (!input.id) throw new TypeError("Record2 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 3, with the audit fields every table in this schema carries. */
export interface Record3 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord3(input: Partial<Record3>): Record3 {
  if (!input.id) throw new TypeError("Record3 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 4, with the audit fields every table in this schema carries. */
export interface Record4 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord4(input: Partial<Record4>): Record4 {
  if (!input.id) throw new TypeError("Record4 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 5, with the audit fields every table in this schema carries. */
export interface Record5 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord5(input: Partial<Record5>): Record5 {
  if (!input.id) throw new TypeError("Record5 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 6, with the audit fields every table in this schema carries. */
export interface Record6 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord6(input: Partial<Record6>): Record6 {
  if (!input.id) throw new TypeError("Record6 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 7, with the audit fields every table in this schema carries. */
export interface Record7 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord7(input: Partial<Record7>): Record7 {
  if (!input.id) throw new TypeError("Record7 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 8, with the audit fields every table in this schema carries. */
export interface Record8 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord8(input: Partial<Record8>): Record8 {
  if (!input.id) throw new TypeError("Record8 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 9, with the audit fields every table in this schema carries. */
export interface Record9 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord9(input: Partial<Record9>): Record9 {
  if (!input.id) throw new TypeError("Record9 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 10, with the audit fields every table in this schema carries. */
export interface Record10 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord10(input: Partial<Record10>): Record10 {
  if (!input.id) throw new TypeError("Record10 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 11, with the audit fields every table in this schema carries. */
export interface Record11 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord11(input: Partial<Record11>): Record11 {
  if (!input.id) throw new TypeError("Record11 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 12, with the audit fields every table in this schema carries. */
export interface Record12 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord12(input: Partial<Record12>): Record12 {
  if (!input.id) throw new TypeError("Record12 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 13, with the audit fields every table in this schema carries. */
export interface Record13 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord13(input: Partial<Record13>): Record13 {
  if (!input.id) throw new TypeError("Record13 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 14, with the audit fields every table in this schema carries. */
export interface Record14 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord14(input: Partial<Record14>): Record14 {
  if (!input.id) throw new TypeError("Record14 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 15, with the audit fields every table in this schema carries. */
export interface Record15 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord15(input: Partial<Record15>): Record15 {
  if (!input.id) throw new TypeError("Record15 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 16, with the audit fields every table in this schema carries. */
export interface Record16 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord16(input: Partial<Record16>): Record16 {
  if (!input.id) throw new TypeError("Record16 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 17, with the audit fields every table in this schema carries. */
export interface Record17 extends Entity {
  name: string
  slug: string
  ordinal: number
  enabled: boolean
  metadata: Record<string, string | number | null>
}

export function normalizeRecord17(input: Partial<Record17>): Record17 {
  if (!input.id) throw new TypeError("Record17 requires an id")
  return {
    id: input.id,
    createdAt: input.createdAt ?? new Date(0),
    updatedAt: input.updatedAt ?? new Date(0),
    name: input.name ?? '',
    slug: (input.slug ?? '').toLowerCase(),
    ordinal: Number.isInteger(input.ordinal) ? (input.ordinal as number) : 0,
    enabled: input.enabled === true,
    metadata: input.metadata ?? {},
  }
}

/** Domain record number 18, with the audit fields every table in this schema carries. */
